# Generated by Django 6.0.2 on 2026-02-24 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
