# Generated by Django 6.0 on 2026-02-19 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('students', '0001_initial'),
        ('students_classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_payments', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.feecategory'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='students_classroom.standard'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('standard', 'category')},
        ),
    ]
