# Generated by Django 6.0 on 2026-02-19 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('students_classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='target_standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_classroom.standard'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='exams.exam'),
        ),
    ]
